# .github/workflows/scheduled-search.yml (수정)

name: Scheduled Naver Search

on:
  schedule:
    # 30분마다 실행
    - cron: '*/30 * * * *'
  # 수동 실행 옵션
  workflow_dispatch:
    inputs:
      mode:
        description: '실행 모드'
        required: true
        default: 'PROD'
        type: choice
        options:
          - PROD
          - DEV
      search_keyword:
        description: '검색 키워드'
        required: true
        default: ''

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # 자동 커밋/푸시를 위해 write 권한 필요

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 설정
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Maven 캐시 설정 (선택 사항)
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Maven 빌드
        run: mvn -B clean package --file pom.xml

      - name: Application 실행
        env:
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          MODE: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.mode || vars.MODE }}
          SEARCH_KEYWORD: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.search_keyword || vars.SEARCH_KEYWORD }}
          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
        run: |
          mkdir -p output
          java -jar target/naver-search-v2-1.0-SNAPSHOT.jar

      - name: Artifact 업로드 (선택 사항)
        uses: actions/upload-artifact@v4
        with:
          name: search-results-excel
          path: output/*.xlsx

      - name: 변경사항 커밋 및 푸시
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "자동 실행 결과 업데이트: ${{ github.workflow }} at $(date +'%Y-%m-%d %H:%M:%S')"
          file_pattern: output/*.xlsx
          commit_user_name: ${{ github.repository_owner }}
          commit_user_email: ${{ github.repository_owner }}@users.noreply.github.com
          commit_author: "${{ github.repository_owner }} <${{ github.repository_owner }}@users.noreply.github.com>"
          skip_dirty_check: false
          # token: ${{ secrets.MY_PUSH_TOKEN }}  # 제거! v5에서는 필요 없음